### ISSUE TITLE
rxdb-premium and react-native-sqlite-2 in expo

### ISSUE THREAD

**Issue by meabed** [pubkey/rxdb#4497]
Hi,
Rxdb premium fails with react-native-sqlite-2

it only with with https://github.com/ospfranco/react-native-quick-sqlite - ( but react-native-quick-sqlite fails on android / expo )

There is a typing issue ( setPragma ) and it through unknown unhandled error in syncing.

**Comment by pubkey** [comment]
Does it fail on iOS, on android or both?
Is there any error message?

**Comment by meabed** [comment]
On iOS

**Comment by pubkey** [comment]
Can you enable the logging?

const storage = getRxStorageSQLite({
  sqliteBasics: getSQLiteBasicsCapacitor(sqlite, Capacitor),
  // pass log function
  log: console.log.bind(console)
});

**Comment by meabed** [comment]
the error with log looks like this:


```
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not a function
TypeError: undefined is not a function
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:216896:15)
    at ?anon_0_ (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:216956:35)
    at next (native)
    at asyncGeneratorStep (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:4638:26)
    at _next (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:4657:29)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:4662:14)
    at tryCallTwo (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:61:9)
    at doResolve (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:216:25)
    at Promise (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:82:14)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:4654:25)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:216959:28)
    at tryCallOne (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/distiller/react-native/sdks/hermes/build_iphonesimulator/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:29738:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:29657:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:29687:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:29850:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:2787:46)
    at anonymous (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:2599:45)
    at __guard (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:2771:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:2598:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.mobile.app:2592:33)
 DEBUG  7:55:58 PM | DEBUG : [RxDB] Cannot create farm replication, dbName or farm collection is not available


```

**Comment by pubkey** [comment]
Does your premium version differ from your rxdb version?

**Comment by meabed** [comment]
it's the same "14.1.2"

**Comment by pubkey** [comment]
I think I found the error. Let me release a new version.

**Comment by pubkey** [comment]
I released `14.1.3`, please try it out.

**Comment by meabed** [comment]
Thank you trying it now.

**Comment by meabed** [comment]
The issue still persist: 



```
 LOG  ## RxStorage SQLite log: open(0) insights-db-v5-62dbc263c1b40d5fcdb6be31
 LOG  ## RxStorage SQLite log: open(0) DONE
 LOG  ## RxStorage SQLite log: setPragma(1) {"key":"synchronous","value":"normal"}
 LOG  ## RxStorage SQLite log: open(2) todo-db-v6-62dbc263c1b40d5fcdb6be31
 LOG  ## RxStorage SQLite log: open(2) DONE
 LOG  ## RxStorage SQLite log: setPragma(3) {"key":"synchronous","value":"normal"}
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not a function
TypeError: undefined is not a function
```

**Comment by pubkey** [comment]
Sorry for the inconvenience.
Please try out the latest version `14.1.5`

**Comment by meabed** [comment]
Thank you 🙏 

Still failing, the error log is:

```
 LOG  ## RxStorage SQLite log: setPragma(1) ERROR
 ERROR  1:59:47 PM | ERROR : [RxDB] error creating collections
{
  "_websqlDatabase": {
    "version": "1.0",
    "_db": {
      "_name": "todo-db-v6-62dbc263c1b40d5fcdb6be31"
    },
    "_txnQueue": {
      "length": 0
    },
    "_running": true,
    "_currentTask": {
      "readOnly": false
    }
  },
  "_error": null,
  "_complete": true,
  "_runningTimeout": false,
  "_sqlQueue": {
    "length": 0
  },
  "_running": false
}
WARN  Possible Unhandled Promise Rejection (id: 0):
WebSQLTransaction {
  "_complete": true,
  "_error": null,
  "_running": false,
  "_runningTimeout": false,
  "_sqlQueue": Queue {
    "first": undefined,
    "last": undefined,
    "length": 0,
  },
  "_websqlDatabase": WebSQLDatabase {
    "_currentTask": null,
    "_db": SQLiteDatabase {
      "_name": "todo-db-v6-62dbc263c1b40d5fcdb6be31",
    },
    "_running": false,
    "_txnQueue": Queue {
      "first": undefined,
      "last": undefined,
      "length": 0,
    },
    "version": "1.0",
  },
}

**Comment by pubkey** [comment]
While reproducing, I stumpled across [this problem](https://github.com/craftzdog/react-native-sqlite-2/issues/96) so it will take me a while to reproduce. Which react-native version are you using?

I found that WebSQL logs errors differently, so the error log that you have posted, contains the transaction objects, not the errors. I will make a new release shortly which fixes that.

**Comment by meabed** [comment]
I am using latest 0.71.3 - I don't think it is that issue. 
The old version of rxdb and pouchdb is working on same setup ( the only change is rxdb )

**Comment by pubkey** [comment]
I released 14.1.8 which fixes the error logs and might also fix the error itself.

**Comment by meabed** [comment]
Thank you - got the error now:

```
 LOG  ## RxStorage SQLite log: run(1) ERROR
 LOG  open transaction error (will retry):
 LOG  {"name":"Error","message":"Error code 1: cannot start a transaction within a transaction","stack":"Error: Error code 1: cannot start a transaction within a transaction\n    at anonymous (http://localhost:8081/index.bun
```

**Comment by pubkey** [comment]
@meabed I found the root cause and I am working on it. I will update you when it is fixed. This will take some days because I have to improve the CI to add tests for WebSQL.

**Comment by pubkey** [comment]
I released version `14.1.9` with a fix.
This is unit tested against the [websql library](https://www.npmjs.com/package/websql).
It does not use the WebSQL API but instead accesses the internal sqlite object. `._db` and uses the `exec()` method from there.
I tried to rewrite everything so that it is compatible with the browser WebSQL API but this is not possible at the moment because of how WebSQL works.

**Comment by meabed** [comment]
@pubkey I just tested and it works 🚀 Thank you

**Comment by pubkey** [comment]
Great. I am closing this. If you find any more problems, please `@` me so I can see it.

**Comment by jwallet** [comment]
@meabed hey there. how did you make it work with expo? can you tell me on which versions you are? sdk, expo, react-native and react-native-sqllite2 ?
